#!/bin/sh
gcc -E tables.c -DENABLE_KOBOLD -DENABLE_MAIA -DENABLE_STANCES -DENABLE_DRACONIAN_TRAITS -DENABLE_MCRAFT -DENABLE_OCCULT -DENABLE_DEATHKNIGHT -DENABLE_HELLKNIGHT -DENABLE_CPRIEST > clean
cat clean | ./tableparser.pl > new-skills.js
